### ISSUE TITLE
Better usability by using cursors or similar

### ISSUE THREAD

**Issue by froth** [medeia/medeia#12]
Currently when writing codecs and navigating through BsonDocuments we are working with a Java library which returns null values and similar stuff. Would be great to have something, that is null safe and maybe also gives context of the current parse-state for better error handling("parsing failed at key->key2->idField"). Have a look at circe cursor.

**Comment by markus1189** [comment]
Alternative that could be tried: write a DSL (final tagless for example) that can be used in order to hide the  Java BSON API.

Although it would be quite possible that one implementation of that DSL just delegates to `Cursor`, seems like a Cursor implementation would be helpful anyway.

I will try to draft a DSL solution soon

**Comment by markus1189** [comment]
I did a quick prototype on how Haskell's `aeson` package does handwritten instances:

https://github.com/medeia/medeia/blob/decoder-dsl/src/main/scala/medeia/dsl/MedeiaDsl.scala

Notes:
- :heavy_check_mark: very simple
- :heavy_check_mark: we could hide bsondocument behind MedeiaDocument
- :heavy_check_mark: integrates well with BsonDecoder typeclass
- :negative_squared_cross_mark: error messages don't provide a stack
  (could we add
- :negative_squared_cross_mark: requires more cats usage like
  `parMapN` and requires imports (Solve this via Tutorial and/or
  mixing in the syntax traits into some medeia type would improve
  this)

**Comment by froth** [comment]
:+1: :happy_ocotopus:
The only thing that bothers me is the last one. As we add a "minimum cats knowledge" entry barrier to medeia. This is a path that we already stumbled into with using `EitherNec` in the `BsonDecoder` interface. A beginner scala developer will not find the interface and parMapN very easy to approach. However the question is: does a beginner really search for a type class based bson encoding library?

I also think that, when we do parMapN inside the generic decoders we should have documentation of why we do it and how to do error accumulating decoders yourself. And then we are in the realm of parMapN anyways. My gut feeling says: we need something that helps with error accumulating anyways and I do not want to maintain two api's (like circe does). 

Short things short: I like!

**Comment by froth** [comment]
Additional thought:

With your idea we do not get the full "cursor" functionality, so you can not traverse a bson without writing or using Decoders/Encoders. But I think this is not a bad thing to provide a reduced api as there is already the normal bson-api for doing low level stuff. If we implement it the way you drafted it is clear how it is intended to be used. "Take a document, fetch keys and delegate to decoders". I am even unsure if we even need a MedeiaArray. 

Maybe we should think about data migration usecases:
"If field version is v2 then decode bsonfield A to case-class field A, if not decode bsonfieldB which only exists in v3" 
This might help to refine the api and see if it is powerful enough.

**Comment by froth** [comment]
After some years of working with this library I am content with how it works for now. We tend to not write instances by hand but create DTOs with derived instances. If a need for something like this arises in the future I am happy to have a look or accepting MRs.

Closing for now.
