### ISSUE TITLE
Support tuples

### ISSUE THREAD

**Issue by markus1189** [medeia/medeia#16]
design decision:

- use Array like Circe
- use Document with some artificial keys like "_1", "_2" etc

**Comment by froth** [comment]
I am quite unsure when I would actually use tuples. 
Therefore I don't have a strong opinion. The Document encoding looks rather awkward in json so I think I would go with array. Not really convinced in any direction however.

**Comment by markus1189** [comment]
I agree that it is better to use a custom case class, but sometimes it's really awkward having to create a dummy 

```
case class FooAndBar(foo: Foo, bar: Bar)
```

just to be able to encode/decode a `List[(Foo,Bar)]`.

We could use sbt-boilerplate or we could write it by hand...

**Comment by froth** [comment]
Or we could do tuple -> hlist -> bson but I think boilerplate would be best. Or we offer free beer for every tuple encoder and crowdfund this.

**Comment by froth** [comment]
I think I won't implement this until someone really needs it. Until then I will close this.
