### ISSUE TITLE
Support Enumeratum

### ISSUE THREAD

**Issue by markus1189** [medeia/medeia#17]
We could support enumeratum enums mechanically, but we would have to pull in the library or do some other tricks

**Comment by froth** [comment]
Or we wait until enumeratum supports us, like it does circe. They don't have a choice, have they? ;)
https://beachape.com/blog/2016/04/16/enumeratum-1-dot-4-valueenums-plus-circe/

**Comment by markus1189** [comment]
Okay then we'll wait until we have replaced ALL JSON libraries with medeia.

In the meantime however we /could/ support this by having a separate sub-module `medeia-enumeratum` that you can pull in if you need it

**Comment by froth** [comment]
Or a `medeia-additonal-codecs` module where we group the stuff that pulls dependencies in?
I am quite unsure if we 2 or 20 or 200 libs for which we want to provide codecs for.
