### ISSUE TITLE
Provide something similar to iemap for Codecs

### ISSUE THREAD

**Issue by froth** [medeia/medeia#202]
Exactly this or something very similar would be helpful.

https://github.com/circe/circe/blob/70e3c4e742ca0181f5c1ce5900e2c71f05ca7ca8/modules/core/shared/src/main/scala/io/circe/Codec.scala#L24

**Comment by L7R7** [comment]
I'd be happy to give it a try and implement it if that's ok for you

**Comment by froth** [comment]
sure :+1:

**Comment by froth** [comment]
closed by #213
