### ISSUE TITLE
Publish for 2.13 (and 2.11?)

### ISSUE THREAD

**Issue by nilskp** [medeia/medeia#88]
Any chance of getting this published for 2.13? And if possible, 2.11.

**Comment by froth** [comment]
It actually is published for 2.13: https://search.maven.org/search?q=a:medeia_2.13

I have no current plans for 2.11. I think it would be possible to cross build with maybe minor adjustments. Pull requests are welcome :)

If you are giving medeia a try: feedback on interface and implementation is always very welcome!

**Comment by nilskp** [comment]
Ah, got it. You might want to change the Maven Central badge link to be https://search.maven.org/search?q=g:%22de.megaera%22 instead.

**Comment by froth** [comment]
Good point, will do!
